name: Sync Sigstore Enrollment

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    uses: freedomofpress/webcat-cli/.github/workflows/sigstore-enrollment-sync.yml@main
    with:
      source-repository-uri: "https://github.com/${{ github.repository }}"
      source-repository-ref: "refs/heads/main"
      build-signer-uri: "https://github.com/${{ github.repository }}/.github/workflows/build.yml@refs/heads/main"
      max_age: "5184000"
